dependencies:  
  - python=3  
  - pip:    
    - ipykernel    
    - pandas   
    - sklearn
    - numpy
    - tensorflow
    - tflearn
    - sklearn.preprocessing
    - sklearn.model_selection
    - sklearn.metrics
