dependencies:  
  - python=3  
  - pip:    
    - ipykernel    
    - pandas   
    - sklearn
    - numpy
    - tensorflow
    - tflearn
    - LabelEncoder
    - OneHotEncoder
    - train_test_split
    - StandardScaler
    - tree
    - classification_report

